window.stockData = {
  "summary": {
    "last_updated": "29-Aug-2026 04:00:30 AM IST (Indian Standard Time)",
    "total_stocks_scanned": 1,
    "swing_top_20_count": 1,
    "strong_buys_count": 0,
    "pattern_breakouts_count": 0,
    "upcoming_3d_events_count": 1,
    "scan_time_seconds": 5.4
  },
  "top_20_swing": [
    {
      "symbol": "512068.BO",
      "clean_symbol": "512068",
      "name": "Deccan Gold Mines Ltd",
      "sector": "Spark Watchlist",
      "cap_type": "Equity",
      "tracking_notes": "Google Sheet Spark Stock List",
      "current_price": 229.45,
      "prev_close": 230.9,
      "day_change_pct": -0.63,
      "volume": 205776,
      "vol_1m_avg": 445474,
      "vol_surge_ratio": 0.46,
      "52w_high": 250.65,
      "52w_low": 83.75,
      "sma_20": 224.68,
      "sma_50": 208.87,
      "sma_200": 143.14,
      "rsi_14": 55.5,
      "macd_val": 10.03,
      "macd_signal": 10.65,
      "macd_hist": -0.61,
      "pe_ratio": 0.0,
      "roe": 0.0,
      "debt_to_equity": 0.0,
      "debt_status": "Zero Debt",
      "debt_score_penalty": 0,
      "rev_growth_yoy": 0.0,
      "earnings_growth_yoy": 0.0,
      "dividend_yield": 0.0,
      "promoter_holding": 50.0,
      "institutional_holding": 30.0,
      "pledged_pct": 0.0,
      "primary_pattern": "Range Consolidation",
      "pattern_bias": "Neutral",
      "pattern_confidence": 60,
      "breakout_level": 250.65,
      "pattern_description": "Stock trading in a sideways consolidation range.",
      "accumulation_status": "Institutional Accumulation \ud83d\udd25",
      "is_volume_dryup": false,
      "breakout_summary": "Consolidation Range",
      "is_20d_high_breakout": false,
      "is_50d_box_breakout": false,
      "is_nr7_expansion": false,
      "is_52w_high_breakout": false,
      "buy_trigger_price": 250.9,
      "sell_trigger_price": 221.31,
      "buy_status": "\u26a1 BUY ABOVE \u20b9250.90 (9.3% away)",
      "swing_target_1": 250.65,
      "swing_target_2": 282.78,
      "swing_stoploss": 221.31,
      "breakout_proximity_pct": 9.2,
      "is_near_breakout_zone": false,
      "breakout_readiness_score": 25.1,
      "composite_score": 34,
      "long_term_signal": "REDUCE / AVOID",
      "swing_signal": "NEUTRAL / WATCH \u2696\ufe0f",
      "swing_reason": "Stock trading in a sideways consolidation range.",
      "events": [
        {
          "date": "2026-08-29",
          "date_tag": "Today",
          "is_upcoming_3_days": true,
          "type": "Trading Monitoring",
          "title": "Normal Volume & Price Watch",
          "summary": "Stock trading smoothly at \u20b9229.45.",
          "impact": "Neutral \u2696\ufe0f",
          "impact_reason": "Standard price discovery."
        }
      ],
      "ai_suggestion": "**ACCUMULATE ON DIPS - BUY TRIGGER: \u20b9250.90** \u2022 Consolidating in **Range Consolidation** base (Consolidation Range). Volume RVOL: 0.46x. \u2022 **Sell/Stop Loss Trigger:** \u20b9221.31 \u2022 **Target 1:** \u20b9250.65 \u2022 **Target 2:** \u20b9282.78",
      "strengths": [
        "\ud83d\udcc5 Upcoming Event (Today): Trading Monitoring - Normal Volume & Price Watch",
        "\ud83d\udca7 Volume Dynamics: Institutional Accumulation \ud83d\udd25",
        "\ud83d\udee1\ufe0f Zero Debt Balance Sheet",
        "\ud83d\udcc8 Above 200-day EMA (Long-term Bull Trend)",
        "\ud83c\udfaf RSI Bullish Momentum Zone: 55.5"
      ],
      "weaknesses": [
        "No major red flags detected"
      ]
    }
  ],
  "all_stocks": [
    {
      "symbol": "512068.BO",
      "clean_symbol": "512068",
      "name": "Deccan Gold Mines Ltd",
      "sector": "Spark Watchlist",
      "cap_type": "Equity",
      "tracking_notes": "Google Sheet Spark Stock List",
      "current_price": 229.45,
      "prev_close": 230.9,
      "day_change_pct": -0.63,
      "volume": 205776,
      "vol_1m_avg": 445474,
      "vol_surge_ratio": 0.46,
      "52w_high": 250.65,
      "52w_low": 83.75,
      "sma_20": 224.68,
      "sma_50": 208.87,
      "sma_200": 143.14,
      "rsi_14": 55.5,
      "macd_val": 10.03,
      "macd_signal": 10.65,
      "macd_hist": -0.61,
      "pe_ratio": 0.0,
      "roe": 0.0,
      "debt_to_equity": 0.0,
      "debt_status": "Zero Debt",
      "debt_score_penalty": 0,
      "rev_growth_yoy": 0.0,
      "earnings_growth_yoy": 0.0,
      "dividend_yield": 0.0,
      "promoter_holding": 50.0,
      "institutional_holding": 30.0,
      "pledged_pct": 0.0,
      "primary_pattern": "Range Consolidation",
      "pattern_bias": "Neutral",
      "pattern_confidence": 60,
      "breakout_level": 250.65,
      "pattern_description": "Stock trading in a sideways consolidation range.",
      "accumulation_status": "Institutional Accumulation \ud83d\udd25",
      "is_volume_dryup": false,
      "breakout_summary": "Consolidation Range",
      "is_20d_high_breakout": false,
      "is_50d_box_breakout": false,
      "is_nr7_expansion": false,
      "is_52w_high_breakout": false,
      "buy_trigger_price": 250.9,
      "sell_trigger_price": 221.31,
      "buy_status": "\u26a1 BUY ABOVE \u20b9250.90 (9.3% away)",
      "swing_target_1": 250.65,
      "swing_target_2": 282.78,
      "swing_stoploss": 221.31,
      "breakout_proximity_pct": 9.2,
      "is_near_breakout_zone": false,
      "breakout_readiness_score": 25.1,
      "composite_score": 34,
      "long_term_signal": "REDUCE / AVOID",
      "swing_signal": "NEUTRAL / WATCH \u2696\ufe0f",
      "swing_reason": "Stock trading in a sideways consolidation range.",
      "events": [
        {
          "date": "2026-08-29",
          "date_tag": "Today",
          "is_upcoming_3_days": true,
          "type": "Trading Monitoring",
          "title": "Normal Volume & Price Watch",
          "summary": "Stock trading smoothly at \u20b9229.45.",
          "impact": "Neutral \u2696\ufe0f",
          "impact_reason": "Standard price discovery."
        }
      ],
      "ai_suggestion": "**ACCUMULATE ON DIPS - BUY TRIGGER: \u20b9250.90** \u2022 Consolidating in **Range Consolidation** base (Consolidation Range). Volume RVOL: 0.46x. \u2022 **Sell/Stop Loss Trigger:** \u20b9221.31 \u2022 **Target 1:** \u20b9250.65 \u2022 **Target 2:** \u20b9282.78",
      "strengths": [
        "\ud83d\udcc5 Upcoming Event (Today): Trading Monitoring - Normal Volume & Price Watch",
        "\ud83d\udca7 Volume Dynamics: Institutional Accumulation \ud83d\udd25",
        "\ud83d\udee1\ufe0f Zero Debt Balance Sheet",
        "\ud83d\udcc8 Above 200-day EMA (Long-term Bull Trend)",
        "\ud83c\udfaf RSI Bullish Momentum Zone: 55.5"
      ],
      "weaknesses": [
        "No major red flags detected"
      ]
    }
  ],
  "upcoming_3d_events": [
    {
      "date": "2026-08-29",
      "date_tag": "Today",
      "is_upcoming_3_days": true,
      "type": "Trading Monitoring",
      "title": "Normal Volume & Price Watch",
      "summary": "Stock trading smoothly at \u20b9229.45.",
      "impact": "Neutral \u2696\ufe0f",
      "impact_reason": "Standard price discovery.",
      "symbol": "512068.BO",
      "clean_symbol": "512068",
      "name": "Deccan Gold Mines Ltd"
    }
  ]
};